Update freeswitch

diff --git a/init.d/freeswitch b/init.d/freeswitch
--- a/init.d/freeswitch
+++ b/init.d/freeswitch
@@ -1,33 +1,30 @@
 #!/bin/bash
 #
-# freeswitch:       Starts the freeswitch Daemon
+#       /etc/rc.d/init.d/freeswitch
 #
-# chkconfig: 345 90 02
-# description: FreeSwitch Open Source Telephony Platform
-### BEGIN INIT INFO
-# Provides: $freeswitch
-# Required-Start: $local_fs
-# Required-Stop: $local_fs
-# Default-Start:  2 3 4 5
-# Default-Stop: 0 1 6
-# Short-Description: Freeswitch
-# Description: Freeswitch
-
-### END INIT INFO
+#       The FreeSwitch Open Source Voice Platform
+#
+#  chkconfig: 345 89 14
+#  description: Starts and stops the freeswitch server daemon
+#  processname: freeswitch
+#  config: /usr/local/freeswitch/conf/freeswitch.conf
+#  pidfile: /usr/local/freeswitch/run/freeswitch.pid
+#
 
 # Source function library.
 . /etc/init.d/functions
-. /etc/sysconfig/network
 
 PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/freeswitch/bin
-DESC="FreeSwitch Open Source Telephony Platform"
-NAME=freeswitch
-DAEMON=/usr/local/freeswitch/bin/$NAME
-PIDFILE=/usr/local/freeswitch/run/$NAME.pid
-prog=freeswitch
-FS_USER=freeswitch
+PROG_NAME=freeswitch
+PID_FILE=${PID_FILE-/usr/local/freeswitch/run/freeswitch.pid}
+FS_USER=${FS_USER-freeswitch}
+FS_FILE=${FS_FILE-/usr/local/freeswitch/bin/freeswitch} 
+FS_HOME=${FS_HOME-/usr/local/freeswitch}
+LOCK_FILE=/var/lock/subsys/freeswitch
+FREESWITCH_ARGS="-nc -rp"
+RETVAL=0
 
-do_setlimits() {
+setlimits() {
         ulimit -c unlimited
         ulimit -d unlimited
         ulimit -f unlimited
@@ -42,49 +39,71 @@ do_setlimits() {
         return 0
 }
 
-# source to get FREESWITCH_OPTIONS
-[ -f /etc/sysconfig/freeswitch ] && . /etc/sysconfig/freeswitch
+if [ -f /etc/sysconfig/freeswitch ]; then
+	. /etc/sysconfig/freeswitch
+fi
 
-do_start() {
-  echo -n $"Starting $prog: "
-        do_setlimits
-        $DAEMON -nc $FREESWITCH_OPTIONS &>/dev/null
-        RETVAL=$?
-  [ $RETVAL -eq 0 ] && success || failure
-        echo 
+start() {
+        echo -n "Starting $PROG_NAME: "
+		setlimits
+        if [ -e $LOCK_FILE ]; then
+            if [ -e $PID_FILE ] && [ -e /proc/`cat $PID_FILE` ]; then
+                echo
+                echo -n $"$PROG_NAME is already running.";
+                failure $"$PROG_NAME is already running.";
+                echo
+                return 1
+            fi
+        fi
+	cd $FS_HOME
+        daemon --user $FS_USER --pidfile $PID_FILE "$FS_FILE $FREESWITCH_ARGS $FREESWITCH_PARAMS >/dev/null 2>&1"
+		RETVAL=$?
+		echo
+        [ $RETVAL -eq 0 ] && touch $LOCK_FILE;
+	echo
         return $RETVAL
 }
 
-do_stop() {
-	echo -n $"Shutting down $prog: "
-        $DAEMON -stop &>/dev/null
-        RETVAL=$?
-	[ $RETVAL -eq 0 ] && success || failure
-        echo
+stop() {
+        echo -n "Shutting down $PROG_NAME: "
+        if [ ! -e $LOCK_FILE ]; then
+            echo
+            echo -n $"cannot stop $PROG_NAME: $PROG_NAME is not running."
+            failure $"cannot stop $PROG_NAME: $PROG_NAME is not running."
+            echo
+            return 1;
+        fi
+	cd $FS_HOME
+	$FS_FILE -stop > /dev/null 2>&1
+        killproc $PROG_NAME
+	RETVAL=$?
+	echo
+	[ $RETVAL -eq 0 ] &&  rm -f $LOCK_FILE;
         return $RETVAL
 }
 
-# See how we were called.
+rhstatus() {
+	status $PROG_NAME;
+}
+
 case "$1" in
-  start)
-        do_start
+    start)
+        start
         ;;
-  stop)
-        do_stop
+    stop)
+        stop
         ;;
-  restart)
-        do_stop
-        echo "Waiting for daemon to exit..."
-        sleep 5
-        do_start
+    status)
+        status $PROG_NAME
+	RETVAL=$?
         ;;
-  status)
-        status -p $PIDFILE freeswitch
+    restart)
+        stop
+        start
         ;;
-  *)
-        echo $"Usage: $0 {start|stop|restart|status}"
-        exit 2
+    *)
+        echo "Usage: $PROG_NAME {start|stop|status|restart}"
+        exit 1
         ;;
 esac
-
 exit $RETVAL
